#pragma config(Sensor, dgtl9,  quadRight,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, quadLeft,       sensorQuadEncoder)
#pragma config(Motor,  port2,           left1,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           right1,        tmotorVex393, openLoop)
#pragma config(Motor,  port4,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

const float L_FACTOR = 0.35;

void setR(int speed)
{
	motor[right1] = motor[right2] = speed;
}

void setL(int speed)
{

	motor[left1] = motor[left2] = speed * L_FACTOR;
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (1)
	{
		setL(vexRT[Ch3]);
		setR(vexRT[Ch2]);
	}
}
