#pragma config(Sensor, dgtl1,  piston,         sensorDigitalOut)
#pragma config(Sensor, dgtl2,  btn,            sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int btnDown = 5;
while (1)
{
	if(!SensorValue[btn] && btnDown<0)
	{
		btnDown = 5;
		SensorValue[piston] = !SensorValue[piston];
	}
	else if (SensorValue[btn])
	{
		btnDown--;
		wait1MSec(10);
	}
}

}
