#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ime,            sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           test,          tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (1)
	{
		motor[test] = vexRT[Ch2];
	}

}
