#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           port4Test,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          right2,        tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Set the right motors to speed speed
void setR(int speed)
{
	//Set the right motors to speed speed
	motor[right1] = motor[right2] = speed;
}

//Set the left motors to speed speed
void setL(int speed)
{
	//Set the left motors to speed speed
	motor[left1] = motor[left2] = speed;
}

void lift(int speed, bool up = true)
{
		motor[lift1] = motor[lift2] = -(motor[lift3] = motor[lift4] = speed * (up?1:-1));
}

void liftB(int speed, bool up = true)
{
		motor[liftB1] = motor[liftB2] = speed * (up?1:-1);
}

void intake(int speed)
{
	motor[in1] = motor[in2] = speed;
}

task main()
{

	while(1)
	{
		//Set the right motor to the speed of the channel 2 input
		setR(vexRT[Ch2]);
		//Set the left motor to the speed of the channel 3 input
		setL(vexRT[Ch3]);

		motor[

}
