#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ime_lift,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ime_right,      sensorNone)
#pragma config(Sensor, I2C_3,  ime_left,       sensorNone)
#pragma config(Motor,  port1,           right,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           lift2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           lift3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           lift4,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           liftB1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftB2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           in1,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           in2,           tmotorVex393, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setR(int speed)
{
	motor[right] = speed;
}

void setL(int speed)
{
	motor[left] = speed;
}

void lift(int speed, bool up = true)
{
		motor[lift1] = motor[lift2] = -(motor[lift3] = motor[lift4] = speed * (up?1:-1));
}

void liftB(int speed, bool up = true)
{
		motor[liftB1] = motor[liftB2] = speed * (up?1:-1);
}

void intake(int speed)
{
	motor[in1] = motor[in2] = speed;
}

task main()
{

	while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);

		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(80, true);
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(80, false);
		}
		else
		{
			lift(21);
		}

		if(vexRT[Btn7U] && !vexRT[Btn7D])
		{
			intake(127);
		}
		else if(vexRT[Btn7D] && !vexRT[Btn7U])
		{
			intake(-127);
		}
		else
		{
			intake(10);
		}

		if(vexRT[Btn5U] && !vexRT[Btn5D])
		{
			liftB(127, true);
		}
		else if(vexRT[Btn5D] && !vexRT[Btn5U])
		{
			liftB(127, false);
		}
		else
		{
			liftB(21,false);
		}

	}

}
