#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ime_lift,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ime_right,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ime_left,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port4,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           lift4,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int LIFT_HIGH = 3050;
const int LIFT_LOW = 5;
const int LIFT_SPEED = 96;
const bool UP = 1;
const bool DOWN = 0;

int getEncoder()
{
	return (nMotorEncoder[right2]+nMotorEncoder[left2])/2;
}

void setR(int speed)
{
	motor[right1] = motor[right2] = speed;
}

void setL(int speed)
{
	motor[left1] = motor[left2] = speed;
}

void lift(int speed, bool up = true)
{
	motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = speed * (up?1:-1);
}

void lift(bool dir)
{
	if (dir)
	{
		while (SensorValue[ime_lift] <= LIFT_HIGH)
		{
			motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = LIFT_SPEED;
		}
		motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = 3;
		return;
		//SensorValue[ime_lift] = LIFT_HIGH;
	}
	else
	{
		while (SensorValue[ime_lift] >= LIFT_LOW)
		{
			motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = -LIFT_SPEED;
		}
		motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = 3;
		SensorValue[ime_lift] = 0;
		return;
	}

}

void fwd(int inches)
{
	setL(127);
	setR(127);
	while(getEncoder()<(inches/4)*392);
	setL(0);
	setR(0);
}

void clawControl(int speed)
{
	motor[claw] = speed;
}

task main()
{
	fwd(12);

}
