#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  piston,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ime_left,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ime_right,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ime_lift,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           lift4,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "driveAPI.h"
#include "auton.h"
#include "lcdAPI.h"
#include "diag.h"

int Program;

////////////////////
// PRE-AUTONOMOUS //
////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

	short leftButton = 1;
	short centerButton = 2;
	short rightButton = 4;
	int choice1;
	int choice2;
	Program = 0;
	bLCDBacklight = true;
	bool inMenu = nLCDButtons;
	while(inMenu)
	{
		lcdClear();
		char* c = "\tChoice 1\nBLU\tDiag\tRED";
		lcd_printf(c);
		int code = lcdWaitForBtnClick();
		if (code==leftButton)
		{
			choice1=0b00;
		}
		if (code==rightButton)
		{
			choice1=0b01;
		}
		if (code==centerButton)
		{
			diag();
			lcdClear();
			c="\tChoice 1\nBLU\tDiag\tRED";
			continue;
		}

		lcdClear();
		lcd_printf("\tChoice 2\nAuto\tBack\tPole");
		code = lcdWaitForBtnClick();
		// Display menu 2
		if (code==leftButton)
		{
			choice2=0b00;
		}
		if (code==rightButton)
		{
			choice2=0b10;
		}
		if (code==centerButton)
		{
			continue;
		}
		Program = choice1 + choice2;
		while(1)
		{
			lcdClear();
			switch (Program)
			{
			case 0:
				lcd_printf("\tBLU Auto\nDiag\tOK\tBack");
				break;
			case 1:
				lcd_printf("\tRED Auto\nDiag\tOK\tBack");
				break;
			case 2:
				lcd_printf("\tBLU Pole\nDiag\tOK\tBack");
				break;
			case 3:
				lcd_printf("\tRED Pole\nDiag\tOK\tBack");
				break;
			}
			code = lcdWaitForBtnClick();
			if(code==centerButton)
			{
				inMenu=false;
				break;
			}
			else if (code==leftButton)
				diag();
			else
				break;
		} // while(1)
	} // while(inMenu)
	//claw(false);
	lcdClear();
}

////////////////
// AUTONOMOUS //
////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	lcdClear();
char* disp = (Program==0?"BLU Auto":Program==1?"RED Auto":Program==2?"BLU Pole":"RED Pole");
	displayLCDCenteredString(0, disp);

	switch(Program)
	{
	case 0:
		autonBluAuto();
		break;
	case 1:
		autonRedAuto();
		break;
	case 2:
		autonBluPole();
		break;
	case 3:
		autonRedPole();
		break;
	}

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

//////////////////
// USER CONTROL //
//////////////////

task usercontrol()
{
	// User control code here, inside the loop
	SensorValue[ime_lift] = 0;
	int btnDown = 5;
	int btnDown2 = 5;
	int btnDown3 = 5;
	while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);

		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(LIFT_SPEED, true);
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(LIFT_SPEED, false);
		}
		else
		{
			lift(10, true);
		}

		if(!vexRT[Btn8D] && btnDown<0)
		{
			btnDown = 5;
			SensorValue[piston] = !SensorValue[piston];
		}
		else if (vexRT[Btn8D])
		{
			btnDown--;
			wait1Msec(10);
		}

		if(!vexRT[Btn8R] && btnDown2<0)
		{
			btnDown2 = 5;
			driveMotors(-2,98,DRIVE_F);

		}
		else if (vexRT[Btn8R])
		{
			btnDown2--;
			wait1Msec(10);
		}

		if(!vexRT[Btn7U] && btnDown3<0)
		{
			btnDown3 = 5;
			liftDist(7,70,UP);
		}
		else if (vexRT[Btn7U])
		{
			btnDown3--;
			wait1Msec(10);
		}
	}

}
