#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  turnSel,        sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ime_lift,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ime_right,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ime_left,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port4,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           lift4,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "lcdAPI.h"
#include "diag.h"
#include "driveAPI.h"


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
int Program;
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

  short leftButton = 1;
	short centerButton = 2;
	short rightButton = 4;
  int choice1;
  int choice2;
  bLCDBacklight = true;
 	while(1)
  {
  	lcdClear();
  	char* c = "\tChoice 1\nBLU\tDiag\tRED";
  	lcd_printf(c);
		int code = lcdWaitForBtnClick();
  	if (code==leftButton)
  	{
  		choice1=0;
  	}
  	if (code==rightButton)
  	{
  		choice1=1;
  	}
  	if (code==centerButton)
  	{
  		diag();
  		lcdClear();
  		c="\tChoice 1\nBLU\tDiag\tRED";
  		continue;
  	}

  	lcdClear();
		lcd_printf("\tChoice 2\nAuto\tBack\tPole");
		code = lcdWaitForBtnClick();
    // Display menu 2
  	if (code==leftButton)
  	{
  		choice2=0;
  	}
  	if (code==rightButton)
  	{
  		choice2=2;
  	}
  	if (code==centerButton)
  	{
  		continue;
  	}
	Program = choice1 + choice2;
	bool stillWaiting=true;
	while(stillWaiting)
	{
	lcdClear();
	switch (Program)
	{
		case 0:
			lcd_printf("\tBLU Auto\nBack\tDiag\tBack");
			break;
		case 1:
			lcd_printf("\tRED Auto\nBack\tDiag\tBack");
			break;
		case 2:
			lcd_printf("\tBLU Pole\nBack\tDiag\tBack");
			break;
		case 3:
			lcd_printf("\tRED Pole\nBack\tDiag\tBack");
			break;
	}
	code = lcdWaitForBtnClick();
	if(code==centerButton)
		diag();
	else
		stillWaiting=false;
	}
}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
lcdClear();
char* disp = (Program==0?"BLU Auto":Program==1?"RED Auto":Program==2?"BLU Pole":"RED Pole");
displayLCDCenteredString(0, disp);
displayLCDCenteredString(1,"Running");
setL(-127);
	setR(-127);
	wait1Msec(750);
	setL(0);
	setR(0);
clawControl(80);
	wait1Msec(500);
	clawControl(-40);

	wait1Msec(1000);
	clawControl(0);
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	bool tension = false;
	bool down_7u = false;
	SensorValue[ime_lift] = 0;
	bool lift_running = false;
	while(1)
	{
		nMotorEncoder[claw] = 0;
	SensorValue[ime_lift] = 0;
	bool lift_running = false;
	bool claw_running = false;
	while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);
		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(LIFT_SPEED, true);
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(LIFT_SPEED, false);
		}
		else
		{
			lift(3);
		}

		/*if(vexRT[Btn5U] && !vexRT[Btn5D])
		{
			lift(UP);
		}
		else if(vexRT[Btn5D] && !vexRT[Btn5U])
		{
			lift(DOWN);
		}*/

		if (vexRT[Btn5U] && !vexRT[Btn5D])
		{
			clawControl(-80);
		}
		else if (vexRT[Btn5D] && !vexRT[Btn5U])
		{
			clawControl(80);
		}
		else
		{
			clawControl(-15);
		}

		if (vexRT[Btn7U] && !down_7u)
		{
			clawControl(-15*(tension?1:0));
			tension = !tension;
			down_7u = true;
		}
		else
		{
			down_7u = false;
		}

	}

	}
}
