#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ime_lift,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ime_right,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ime_left,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           claw,          tmotorVex269, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port4,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           lift4,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int CLAW_OPEN = 140;
const int LIFT_HIGH = 3050;
const int LIFT_LOW = 5;
const int LIFT_SPEED = 96;
const bool UP = 1;
const bool DOWN = 0;

void setR(int speed)
{
	motor[right1] = motor[right2] = speed;
}

void setL(int speed)
{
	motor[left1] = motor[left2] = speed;
}

void lift(int speed, bool up = true)
{
	motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = speed * (up?1:-1);
}

void lift(bool dir)
{
	if (dir)
	{
		while (SensorValue[ime_lift] <= LIFT_HIGH)
		{
			motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = LIFT_SPEED;
		}
		motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = 3;
		return;
		//SensorValue[ime_lift] = LIFT_HIGH;
	}
	else
	{
		while (SensorValue[ime_lift] >= LIFT_LOW)
		{
			motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = -LIFT_SPEED;
		}
		motor[lift1] = motor[lift2] = motor[lift3] = motor[lift4] = 3;
		SensorValue[ime_lift] = 0;
		return;
	}

}

void clawControl(int speed)
{
	motor[claw] = speed;
}

void clawFull(bool open)
{
	clawControl(64*(open?1:-1));
	if(open)
	{
		while(nMotorEncoder[claw]<CLAW_OPEN);
	}
	else
	{
		while(nMotorEncoder[claw]>0);
	}
	motor[claw]=5;
}

task main()
{
	nMotorEncoder[claw] = 0;
	SensorValue[ime_lift] = 0;
	bool lift_running = false;
	bool claw_running = false;
	while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);
		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(LIFT_SPEED, true);
			lift_running = true;
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(LIFT_SPEED, false);
			lift_running = true;
		}
		else if (lift_running)
		{
			lift(3);
			lift_running = false;
		}

		/*if(vexRT[Btn5U] && !vexRT[Btn5D])
		{
			lift(UP);
		}
		else if(vexRT[Btn5D] && !vexRT[Btn5U])
		{
			lift(DOWN);
		}*/

		if (vexRT[Btn7U] && !vexRT[Btn7D])
		{
			clawControl(-80);
		}
		else if (vexRT[Btn7D] && !vexRT[Btn7U])
		{
			clawControl(80);
		}
		else
		{
			clawControl(-5);
		}



	}

}
