#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           lift4,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           clawTilt,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "driveAPI.h"
#include "auton.h"
#include "lcdAPI.h"
#include "diag.h"

int Program;

////////////////////
// PRE-AUTONOMOUS //
////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

  short leftButton = 1;
	short centerButton = 2;
	short rightButton = 4;
  int choice1;
  int choice2;
  Program = 0;
  bLCDBacklight = true;
  bool inMenu = nLCDButtons;
  while(inMenu)
  {
  	lcdClear();
  	char* c = "\tChoice 1\nBLU\tDiag\tRED";
  	lcd_printf(c);
		int code = lcdWaitForBtnClick();
  	if (code==leftButton)
  	{
  		choice1=0b00;
  	}
  	if (code==rightButton)
  	{
  		choice1=0b01;
  	}
  	if (code==centerButton)
  	{
  		diag();
  		lcdClear();
  		c="\tChoice 1\nBLU\tDiag\tRED";
  		continue;
  	}

  	lcdClear();
		lcd_printf("\tChoice 2\nAuto\tBack\tPole");
		code = lcdWaitForBtnClick();
    // Display menu 2
  	if (code==leftButton)
  	{
  		choice2=0b00;
  	}
  	if (code==rightButton)
  	{
  		choice2=0b10;
  	}
  	if (code==centerButton)
  	{
  		continue;
  	}
		Program = choice1 + choice2;
		while(1)
		{
			lcdClear();
			switch (Program)
			{
				case 0:
					lcd_printf("\tBLU Auto\nDiag\tOK\tBack");
					break;
				case 1:
					lcd_printf("\tRED Auto\nDiag\tOK\tBack");
					break;
				case 2:
					lcd_printf("\tBLU Pole\nDiag\tOK\tBack");
					break;
				case 3:
					lcd_printf("\tRED Pole\nDiag\tOK\tBack");
					break;
			}
			code = lcdWaitForBtnClick();
			if(code==centerButton)
			{
				inMenu=false;
				break;
			}
			else if (code==leftButton)
				diag();
			else
				break;
		} // while(1)
	} // while(inMenu)
	//claw(false);
	lcdClear();
}

////////////////
// AUTONOMOUS //
////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
	lcdClear();
	char* disp = (Program==0?"BLU Auto":Program==1?"RED Auto":Program==2?"BLU Pole":"RED Pole");
	displayLCDCenteredString(0, disp);

	switch(Program)
	{
		case 0:
			autonBluAuto();
			break;
		case 1:
			autonRedAuto();
			break;
		case 2:
			autonBluPole();
			break;
		case 3:
			autonRedPole();
			break;
	}

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	 while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);

		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(127, false);
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(127, true);
		}
		else
		{
			lift(0);
		}

		if(vexRT[Btn5U] && !vexRT[Btn5D])
		{
			liftSec(127, false);
		}
		else if(vexRT[Btn5D] && !vexRT[Btn5U])
		{
			liftSec(127, true);
		}
		else
		{
			liftSec(10);
		}

		if(vexRT[Btn7L] && !vexRT[Btn7R])
		{
			clawControl(64, true);
		}
		else if(vexRT[Btn7R] && !vexRT[Btn7L])
		{
			clawControl(64, false);
		}
		else
		{
			clawControl(5, false);
		}

		if(vexRT[Btn7U] && !vexRT[Btn7D])
		{
			clawTiltControl(32, true);
		}
		else if(vexRT[Btn7D] && !vexRT[Btn7U])
		{
			clawTiltControl(32, false);
		}
		else
		{
			clawTiltControl(5, true);
		}

	}
	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.

}
