#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           lift4,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           right1,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           lift3,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           clawTilt,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Set the right motors to speed speed
void setR(int speed)
{
	//Set the right motors to speed speed
	motor[right1] = motor[right2] = speed;
}

//Set the left motors to speed speed
void setL(int speed)
{
	//Set the left motors to speed speed
	motor[left1] = motor[left2] = speed;
}

//Control the lift motors
void lift(int speed, bool up = true)
{
	//Sets the lift motors to speed multiplied by direction depending
	//on the values of the up boolean
	motor[lift1] = motor[lift2] = speed * (up?1:-1);
}

//Control the secondary lift motors
void liftSec(int speed, bool up = true)
{
	//Sets the lift motors to speed multiplied by direction depending
	//on the values of the up boolean
	motor[lift3] = motor[lift4] = speed * (up?1:-1);
}

//Control the claw
void clawControl(int speed, bool open)
{
	//Sets the claw motor to speed multiplied by direction depending
	//on the values of the up boolean
	motor[claw] = speed * (open?1:-1);
}

//
void clawTiltControl(int speed, bool up)
{
	motor[clawTilt] = speed * (up?1:-1);
}

task main()
{

	while(1)
	{
		setR(vexRT[Ch2]);
		setL(vexRT[Ch3]);

		if(vexRT[Btn6U] && !vexRT[Btn6D])
		{
			lift(127, false);
		}
		else if(vexRT[Btn6D] && !vexRT[Btn6U])
		{
			lift(127, true);
		}
		else
		{
			lift(0);
		}

		if(vexRT[Btn5U] && !vexRT[Btn5D])
		{
			liftSec(127, false);
		}
		else if(vexRT[Btn5D] && !vexRT[Btn5U])
		{
			liftSec(127, true);
		}
		else
		{
			liftSec(10);
		}

		if(vexRT[Btn7L] && !vexRT[Btn7R])
		{
			clawControl(64, true);
		}
		else if(vexRT[Btn7R] && !vexRT[Btn7L])
		{
			clawControl(64, false);
		}
		else
		{
			clawControl(5, false);
		}

		if(vexRT[Btn7U] && !vexRT[Btn7D])
		{
			clawTiltControl(32, true);
		}
		else if(vexRT[Btn7D] && !vexRT[Btn7U])
		{
			clawTiltControl(32, false);
		}
		else
		{
			clawTiltControl(5, true);
		}

	}

}
